spring:
  application:
    name: securitydemo
  datasource:
    url: jdbc:mysql://localhost:3306/User
    username: root
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
